name: roleplay_kit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dart_openai: ^4.0.0
  envied: ^0.3.0
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

flutter:
  uses-material-design: true
  fonts: 
    - family: reading
      fonts:
        - asset: assets/fonts/KoPubWorld Batang_Pro Medium.otf
        - asset: assets/fonts/KoPubWorld Batang_Pro Light.otf
          weight: 300
        - asset: assets/fonts/KoPubWorld Batang_Pro Bold.otf
          weight: 700
