name: roleplay_kit
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dart_openai: ^1.9.1
  envied: ^0.3.0
  shared_preferences: ^2.0.13
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
